name: 'E2E'
description: 'Run E2E tests'

inputs:
  status_api_key:
    description: 'API key to read job status'
    required: true
  nais_management_project_id:
    description: 'Project ID for nais/logins'
    required: true
  nais_workload_identity_provider:
    description: 'Identity provider for nais/login'
    required: true
  e2e_tag:
    description: 'Tag for E2E image'
    required: false
    default: 'latest'

branding:
  icon: 'shield'
  color: 'green'

outputs:
  image:
    description: 'E2E image'
    value: ${{ steps.image.outputs.image }}
  status:
    description: 'E2E job status'
    value: ${{ steps.status.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Checkout E2E
      uses: actions/checkout@v4
      with:
        repository: navikt/klang-e2e-tests

    - name: Get image registry
      id: image-registry
      uses: nais/login@v0
      with:
        project_id: ${{ inputs.nais_management_project_id }}
        identity_provider: ${{ inputs.nais_workload_identity_provider }}
        team: klage
    
    - name: Generate UUID
      id: uuid
      shell: bash
      run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

    - name: Get image tag
      id: image-tag
      shell: bash
      run: |
        if [[ -n "${{ inputs.e2e_tag }}" ]]; then
          echo "tag=${{ inputs.e2e_tag }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - name: Generate image name
      id: image
      shell: bash
      run: echo "image=${{ steps.image-registry.outputs.registry }}/klang-e2e-tests:${{ steps.image-tag.outputs.tag }}" >> $GITHUB_OUTPUT

    - name: Run E2E tests
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        VAR: jobid=${{ steps.uuid.outputs.uuid }},image=${{ steps.image.outputs.image }}
        TEAM: klage
        RESOURCE: nais/e2e-job.yaml
        IMAGE: ${{ steps.image.outputs.image }}

    - name: Check E2E job status
      id: status
      uses: navikt/klage-job-status/action@main
      with:
        api_key: ${{ inputs.status_api_key }}
        job_id: ${{ steps.uuid.outputs.uuid }}
        fail: true
        fail_on_unknown: true
