apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: klage
    e2e: kabin
  name: kabin-e2e-tests-{{jobid}}
  namespace: klage
spec:
  backoffLimit: 0
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 8000m
      memory: 8Gi  
  image: {{image}}
  envFrom:
  - secret: kabin-e2e-test-users
  - secret: slack-e2e-secrets
  - configmap: slack-e2e-configmap
  accessPolicy:
    outbound:
      external:
      - host: kabin.intern.dev.nav.no
